# http://travis-ci.org/#!/ipython/ipyparallel
language: python
python:
  - "3.8.2"
  - "3.8"
  - "3.9-dev"
  - "nightly"
  - 3.6
  - 2.7
  - 3.5
  - 3.4
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade setuptools pip
  - pip install --pre --upgrade --upgrade-strategy eager .[test] distributed joblib codecov 'tornado<6'
  - |
    # install pinned tornado
    if [[ ! -z "$TORNADO" ]]; then
      pip install tornado==${TORNADO}
    fi
  - 'pip install --only-binary :all: matplotlib || echo "no matplotlib"'
  - pip freeze
script:
  - pytest --maxfail=3 --cov ipyparallel -vsx ipyparallel/tests
after_success:
  - codecov
matrix:
  allow_failures:
    - python: "3.9-dev"
    - python: "nightly"
  include:
    - python: 3.6
      env: TORNADO="4.5.3"
    - python: 2.7
      env: TORNADO="4.5.3"
